stages:
  - build

build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug-v0.14.0
    entrypoint: [""]
  script:
    - executor
      --cache=true  
      --cache-repo $CI_REGISTRY_IMAGE/cache 
      --context $CI_PROJECT_DIR 
      --dockerfile $CI_PROJECT_DIR/docker/Dockerfile 
      --destination $CI_REGISTRY_IMAGE:$CI_DOCKER_TAG 
      --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  tags:
    - docker

