apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elastic-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    {{- if eq .Values.environment "dev"}}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.main.http_white_list }}"
    {{- end}}
    {{- if eq .Values.environment "prod"}}
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.main.http_white_list_vpn }}"
    {{- end}}
    {{- if or (eq .Values.environment "prod") (eq .Values.environment "stage") }}
    ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/server-snippet: |
      more_clear_headers Server;
      more_clear_headers Server service-name;
    {{- end}}
spec:
  {{- if or (eq .Values.environment "prod") (eq .Values.environment "stage") }}
  tls:
  - hosts:
    - {{ .Values.elastic.public_domain }}
    secretName: cert-wildcard
  {{- end}}
  rules:
  - host: {{ .Values.elastic.public_domain }}
    http:
      paths:
        - backend:
            serviceName: elastic
            servicePort: 9200
