apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rabbitmq-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/whitelist-source-range: "{{ .Values.main.http_white_list }}"
    {{- if or (eq .Values.environment "prod") (eq .Values.environment "stage") }}
    #    nginx.ingress.kubernetes.io/auth-type: basic
    #nginx.ingress.kubernetes.io/auth-secret: basic-auth
    #nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    {{- end}}
spec:
  rules:
  - host: {{ .Values.rabbitmq.public_domain }}
    http:
      paths:
      - backend:
          serviceName: rabbitmq
          servicePort: 80
