apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq
spec:
  ports:
  - name: "15672"
    port: 80
    targetPort: 15672
  - name: "5672"
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP
{{if eq .Values.environment "dev"}}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: rabbitmq-external
spec:
  ports:
    - name: "5672"
      port: 5672
      nodePort: {{ .Values.rabbitmq.public_port5672 }}
    - name: "15672"
      port: 15672
      nodePort: {{ .Values.rabbitmq.public_port15672 }}
  selector:
    app: rabbitmq
  type: NodePort
{{end}}
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  selector:
    matchLabels:
      app: rabbitmq
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: {{ .Values.rabbitmq.image }}
        ports:
        - containerPort: 5672
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: "user"
        - name: RABBITMQ_DEFAULT_PASS
          value: "password"
      imagePullSecrets:
      - name: regcred
